"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2 } from "lucide-react";

type ToolKind = "wholesale" | "ready" | "purchase";
const config = {
  wholesale: { title: "Wholesale pricing", endpoint: "/api/calculate/wholesale-pricing", intro: "Turn your real unit cost into a quote you can explain. Margin is profit divided by selling price; multiplier is a separate retail scenario." },
  ready: { title: "Ready-by planner", endpoint: "/api/calculate/production", intro: "Work backward from the date stock needs to be ready. The result is a planning schedule, not a guarantee of cure or production capacity." },
  purchase: { title: "Ingredient purchase planner", endpoint: "/api/calculate/purchasing", intro: "Subtract usable stock from one ingredient requirement, then calculate the packs you actually need to buy." },
} as const;

type Result = Record<string, unknown>;
export function PlanningToolForm({ kind }: { kind: ToolKind }) {
  const [values, setValues] = useState<Record<string, string>>(kind === "wholesale" ? { cost: "2.40", batch: "40", margin: "35", retail: "2" } : kind === "ready" ? { units: "48", yield: "12", ready: "2026-11-15", cure: "42", buffer: "2", lead: "0" } : { name: "Olive oil", required: "2400", onHand: "800", pack: "1000", unit: "g" });
  const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const meta = config[kind];
  const update = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const number = (key: string) => Number(values[key]);
  async function submit(event: FormEvent) {
    event.preventDefault(); setError(""); setResult(null);
    const body = kind === "wholesale" ? { productionCostPerBar: number("cost"), batchSize: number("batch"), desiredMargin: number("margin"), retailMultiplier: number("retail") } : kind === "ready" ? { saleableUnitsRequired: number("units"), expectedYieldPerBatch: number("yield"), readyByDate: values.ready, cureDays: number("cure"), unmoldCutBufferDays: number("buffer"), productionLeadTimeDays: number("lead") } : { ingredientId: "manual-ingredient", ingredientName: values.name || "Ingredient", required: number("required"), onHand: number("onHand"), packSize: number("pack"), unit: values.unit };
    try { const response = await fetch(meta.endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Check the inputs and try again."); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not calculate this plan."); }
  }
  const field = (key: string, label: string, suffix?: string, type = "number", help?: string) => <label className="block text-sm font-medium text-foreground">{label}<span className="mt-2 flex min-h-11 items-center rounded border border-input bg-background focus-within:ring-2 focus-within:ring-ring"><input required type={type} min={type === "number" ? "0" : undefined} step={type === "number" ? "any" : undefined} value={values[key] ?? ""} onChange={(event) => update(key, event.target.value)} className="min-h-11 w-full bg-transparent px-3 outline-none" />{suffix && <span className="pr-3 text-sm text-muted-foreground">{suffix}</span>}</span>{help && <span className="mt-1 block text-xs font-normal text-muted-foreground">{help}</span>}</label>;
  return <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.72fr)]"><form onSubmit={submit} className="border border-border bg-card p-5 sm:p-7"><div className="mb-7"><h2 className="text-section">Enter your numbers</h2><p className="mt-1 text-sm text-muted-foreground">All fields stay in this browser session. Nothing is sent until you press calculate.</p></div><div className="grid gap-5 sm:grid-cols-2">{kind === "wholesale" && <>{field("cost", "Production cost per bar", "$", "number", "Include materials and other costs you actually assign to one saleable bar.")}{field("batch", "Saleable bars in batch", undefined, "number")}{field("margin", "Target gross margin", "%", "number", "Margin = profit ÷ selling price. This is not markup.")}{field("retail", "Retail multiplier", "×", "number", "A separate retail scenario: wholesale price × multiplier.")}</>}{kind === "ready" && <>{field("units", "Saleable units required")}{field("yield", "Saleable units per batch")}{field("ready", "Ready-by date", undefined, "date")}{field("cure", "Chosen cure interval", "days", "number", "Use your process-specific interval; this tool does not certify readiness.")}{field("buffer", "Unmold / cut buffer", "days")}{field("lead", "Other lead time", "days")}</>}{kind === "purchase" && <>{field("name", "Ingredient name", undefined, "text")}{field("required", "Requirement", values.unit, "number")}{field("onHand", "Usable stock on hand", values.unit, "number")}{field("pack", "Pack size", values.unit, "number")}</>}</div><button className="mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-primary px-5 font-semibold text-primary-foreground transition hover:bg-primary/90 sm:w-auto" type="submit">Calculate <ArrowRight className="h-4 w-4" aria-hidden="true" /></button>{error && <p role="alert" className="mt-4 flex gap-2 border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive"><AlertTriangle className="h-4 w-4 shrink-0" aria-hidden="true" />{error}</p>}</form><aside className="h-fit border border-foreground/10 bg-foreground p-6 text-background sm:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-background/55">Result preview</p><p className="mt-4 text-lg leading-8 text-background/80">{meta.intro}</p>{result ? <Result kind={kind} data={result} /> : <div className="mt-8 border-t border-background/15 pt-5 text-sm leading-6 text-background/55">Your result will appear here after calculation.</div>}</aside></div>;
}
function Result({ kind, data }: { kind: ToolKind; data: Result }) {
  const purchase = data.purchases as Array<Record<string, unknown>> | undefined; let rows: [string, string][];
  if (kind === "wholesale") rows = [["Wholesale / bar", `$${Number(data.wholesalePricePerBar).toFixed(2)}`], ["Wholesale / batch", `$${Number(data.wholesalePricePerBatch).toFixed(2)}`], ["Retail / bar", `$${Number(data.retailPricePerBar).toFixed(2)}`], ["Wholesale profit / batch", `$${Number(data.wholesaleProfit).toFixed(2)}`]];
  else if (kind === "ready") rows = [["Batches required", String(data.batchesRequired)], ["Latest pour date", String(data.pourDate).slice(0, 10)]];
  else { const first = purchase?.[0]; rows = [["Shortage", `${Number(first?.shortage ?? 0)} ${String(first?.unit ?? "")}`], ["Packs required", String(first?.packsRequired ?? 0)], ["Quantity to buy", `${String(first?.quantityToBuy ?? 0)} ${String(first?.unit ?? "")}`]]; }
  return <div className="mt-7 border-t border-background/15 pt-6"><div className="space-y-4">{rows.map(([label, value]) => <div className="flex items-end justify-between gap-4" key={label}><span className="text-sm text-background/60">{label}</span><strong className="font-mono text-xl tabular-nums">{value}</strong></div>)}</div><p className="mt-6 flex gap-2 text-xs leading-5 text-background/60"><CheckCircle2 className="h-4 w-4 shrink-0 text-accent" aria-hidden="true" />Planning output only. Confirm your own production, supplier, and pricing assumptions.</p><Link href="/tools" className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-background underline decoration-background/30 underline-offset-4 hover:decoration-background">Continue to another tool <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div>;
}
