// ── Blog Content Template ──────────────────
// Deterministic renderer for programmatic blog posts.
// The template supplies layout, schema, internal links, and the product CTA.
// Records supply the situation-specific substance.
// The agent writes the editorial content; the template handles structure.

import { BlogContentContract, BlogCategory } from "@/lib/blog-contract";

export interface BlogTemplateInput {
  slug: string;
  title: string;
  description: string;
  category: BlogCategory;
  tags: string[];
  author: string;
  readingTime: number;
  seo: {
    title: string;
    description: string;
    keywords: string[];
  };
  // Substantive body content (written by the agent, not generated by the template)
  content: string;
  // Product bridge — which SoapCraft Pro feature does this page connect to?
  productBridge: {
    text: string;
    href: string;
  };
  // Related posts (by slug)
  relatedSlugs?: string[];
  // Source reference for factual claims
  source?: string;
  // Review state
  reviewStatus: BlogContentContract["reviewStatus"];
  lastReviewed?: string;
  reviewer?: string;
}

// ── Render a blog post record ───────────────
// The template produces the structured output; the agent provides the content.

export function renderBlogPost(input: BlogTemplateInput): BlogContentContract {
  const now = new Date().toISOString().split("T")[0];

  return {
    slug: input.slug,
    title: input.title,
    description: input.description,
    content: input.content,
    category: input.category,
    tags: input.tags,
    publishedAt: now,
    author: input.author,
    readingTime: input.readingTime,
    image: `/blog/${input.slug}.png`,
    seo: input.seo,
    reviewStatus: input.reviewStatus,
    source: input.source,
    lastReviewed: input.lastReviewed || now,
    reviewer: input.reviewer,
    relatedSlugs: input.relatedSlugs,
    contextualCTA: input.productBridge
      ? {
          text: input.productBridge.text,
          href: input.productBridge.href,
        }
      : undefined,
  };
}

// ── Validate a rendered post ────────────────
// Checks the content contract before publishing.

export function validateRenderedPost(post: BlogContentContract): {
  valid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Required fields
  if (!post.slug) errors.push("Missing slug");
  if (!post.title) errors.push("Missing title");
  if (!post.description) errors.push("Missing description");
  if (!post.content) errors.push("Missing content");
  if (!post.category) errors.push("Missing category");
  if (!post.tags || post.tags.length === 0) errors.push("Missing tags");
  if (!post.author) errors.push("Missing author");
  if (post.readingTime == null) errors.push("Missing readingTime");

  // SEO
  if (!post.seo?.title) errors.push("Missing seo.title");
  if (!post.seo?.description) errors.push("Missing seo.description");
  if (!post.seo?.keywords || post.seo.keywords.length === 0) {
    errors.push("Missing seo.keywords");
  }

  // Review status
  if (!post.reviewStatus) errors.push("Missing reviewStatus");
  if (post.reviewStatus === "published" && !post.lastReviewed) {
    warnings.push("Published post should have a lastReviewed date");
  }

  // Content quality
  if (post.content) {
    const wordCount = post.content.split(/\s+/).length;
    if (wordCount < 800) {
      warnings.push(`Content is ${wordCount} words — minimum 800 recommended`);
    }

    // Banned phrases
    const bannedPhrases = ["map pin", "I run Web Align", "Googling"];
    for (const phrase of bannedPhrases) {
      if (post.content.toLowerCase().includes(phrase.toLowerCase())) {
        errors.push(`Contains banned phrase: "${phrase}"`);
      }
    }

    // Banned patterns
    const bannedPatterns = [
      /—/, // em dash
      /in today's world/i,
      /it's not just \w+, it's \w+/i,
      /hope this finds you well/i,
      /i am an AI/i,
      /as an AI language model/i,
    ];
    for (const pattern of bannedPatterns) {
      if (pattern.test(post.content)) {
        errors.push(`Contains banned pattern: ${pattern}`);
      }
    }
  }

  // Product bridge
  if (!post.contextualCTA) {
    warnings.push("Missing product bridge — page should reference SoapCraft Pro");
  }

  // Category validation
  const validCategories: BlogCategory[] = [
    "Soap Calculators",
    "Soap Recipes",
    "Soap Making Guides",
    "Troubleshooting",
    "Soap Business",
    "Ingredients",
  ];
  if (post.category && !validCategories.includes(post.category)) {
    errors.push(
      `Invalid category "${post.category}". Must be one of: ${validCategories.join(", ")}`
    );
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}
