export interface IntentEntry {
  path: string;
  primaryKeyword: string;
  intentStage: "product" | "problem" | "informational" | "commercial";
  contentMode: "editorial" | "programmatic";
  productPage?: string;
  reviewStatus: "draft" | "review" | "approved" | "published";
  source?: string;
  lastReviewed?: string;
  internalLinks?: string[];
}

export const intentRegistry: IntentEntry[] = [
  {
    path: "/calculators/soap-cost-calculator",
    primaryKeyword: "soap cost per bar calculator",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/batches/[id]/cost",
    reviewStatus: "published",
    internalLinks: ["/", "/marketing/pricing", "/blog"],
  },
  {
    path: "/compare/soapcalc-alternative",
    primaryKeyword: "soapcalc alternative",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/recipes/new",
    reviewStatus: "published",
    internalLinks: ["/", "/marketing/pricing", "/blog"],
  },
  {
    path: "/soap-recipe-management-software",
    primaryKeyword: "soap recipe management software",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/recipes/new",
    reviewStatus: "published",
    internalLinks: ["/", "/marketing/pricing", "/blog"],
  },
  {
    path: "/soap-batch-tracking-software",
    primaryKeyword: "soap batch tracking software",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/batches/new",
    reviewStatus: "published",
    internalLinks: ["/", "/marketing/pricing", "/blog"],
  },
  {
    path: "/calculators/batch-costing",
    primaryKeyword: "batch costing calculator",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/soap-cost-calculator", "/marketing/pricing", "/blog"],
  },
  {
    path: "/calculators/recipe-scaling",
    primaryKeyword: "recipe scaling calculator",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/recipes/new",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/recipes"],
  },
  {
    path: "/calculators/mold-volume",
    primaryKeyword: "mold volume calculator",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/recipes/new",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/recipes"],
  },
  {
    path: "/calculators/craft-fair-break-even",
    primaryKeyword: "craft fair break even calculator",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/guides/cost-per-bar-deep-dive",
    primaryKeyword: "cost per bar soap formula",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/calculators/batch-costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/guides/ingredient-reorder-calculation",
    primaryKeyword: "soap ingredient reorder point",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/ingredients",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/guides/curing-schedule-optimizer",
    primaryKeyword: "soap curing schedule calculator",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/cure",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/calculators/wholesale-pricing",
    primaryKeyword: "wholesale soap pricing calculator",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/marketing/pricing", "/blog"],
  },
  {
    path: "/pinterest/batch-costing",
    primaryKeyword: "batch costing for soap makers",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/calculators/batch-costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/tiktok/cost-per-bar",
    primaryKeyword: "how much does soap cost to make",
    intentStage: "commercial",
    contentMode: "editorial",
    productPage: "/calculators/batch-costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/craft-fair-inventory-planning",
    primaryKeyword: "craft fair soap inventory planning",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/batch-tracking-for-wholesale",
    primaryKeyword: "batch tracking for wholesale soap",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/batches/new",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/batch-costing-for-soapmakers",
    primaryKeyword: "batch costing for soap makers",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/calculators/batch-costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/how-to-plan-soap-production-for-craft-fair",
    primaryKeyword: "craft fair soap production planning",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/costing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/understanding-lye-safety-in-cold-process-soap",
    primaryKeyword: "lye safety cold process soap",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/safety",
    reviewStatus: "published",
    internalLinks: ["/", "/blog"],
  },
  {
    path: "/blog/mold-selection-guide-for-cold-process-soap",
    primaryKeyword: "cold process soap mold selection",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/recipes/new",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/mold-volume", "/blog"],
  },
  {
    path: "/blog/superfat-explained-why-5-vs-8-matters",
    primaryKeyword: "superfat percentage soap calculator",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/calculators/batch-costing",
    reviewStatus: "published",
    internalLinks: ["/", "/blog"],
  },
  {
    path: "/blog/from-batch-to-shelf-tracking-soap-production",
    primaryKeyword: "soap production tracking system",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/batches/new",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/cold-process-vs-hot-process-soap",
    primaryKeyword: "cold process vs hot process soap",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/recipes/new",
    reviewStatus: "published",
    internalLinks: ["/", "/blog"],
  },
  {
    path: "/blog/fragrance-oil-vs-essential-oil-for-soap",
    primaryKeyword: "fragrance oil vs essential oil soap",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/ingredients",
    reviewStatus: "published",
    internalLinks: ["/", "/blog"],
  },
  {
    path: "/blog/how-to-price-your-soap-for-wholesale",
    primaryKeyword: "wholesale soap pricing calculator",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/calculators/wholesale-pricing",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/wholesale-pricing", "/blog"],
  },
  {
    path: "/blog/soap-ingredient-cost-comparison",
    primaryKeyword: "soap ingredient cost comparison",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/ingredients",
    reviewStatus: "published",
    internalLinks: ["/", "/blog"],
  },
  {
    path: "/blog/setting-up-a-soapmaking-business-legal-basics",
    primaryKeyword: "soapmaking business legal requirements",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/regulations",
    reviewStatus: "published",
    internalLinks: ["/", "/blog"],
  },
  {
    path: "/blog/cure-times-and-what-happens-during-curing",
    primaryKeyword: "soap cure time calculator",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/cure",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/curing-schedule-optimizer", "/blog"],
  },
  {
    path: "/blog/batch-records-why-every-soapmaker-should-keep-them",
    primaryKeyword: "batch records soapmaking",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/batches/new",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/batch-costing", "/blog"],
  },
  {
    path: "/blog/how-to-scale-your-soap-recipe-for-larger-batches",
    primaryKeyword: "recipe scaling calculator soap",
    intentStage: "informational",
    contentMode: "editorial",
    productPage: "/calculators/recipe-scaling",
    reviewStatus: "published",
    internalLinks: ["/", "/calculators/recipe-scaling", "/blog"],
  },
];

export function getIntentEntry(path: string): IntentEntry | undefined {
  return intentRegistry.find((entry) => entry.path === path);
}

export function getPublishedEntries(): IntentEntry[] {
  return intentRegistry.filter(
    (entry) => entry.reviewStatus === "published"
  );
}
