# SoapCraft Pro — Product Requirements Document

**Version:** 1.0 — Comprehensive Anonymous Utility Hub Contract
**Supersedes:** `product/PRD.md` v3.0 (traffic-first/rescue specification), v4.0 traffic-first artifacts
**Approved direction:** `product/PRODUCT-CONTRACT-UTILITY-HUB.md` — approved by Isaac on 2026-09-09
**Status:** Comprehensive contract for the connected public soapmaking utility system
**Companion documents:**
- `product/PRODUCT-CONTRACT-UTILITY-HUB.md` — approved direction contract
- `product/FLOWS.md` — numbered anonymous and optional-account end-to-end flows
- `product/ARCHITECTURE.md` — module boundaries, data ownership, versioning
- `product/DESIGN.md` — visual system, states, interaction patterns
- `product/TOOL-QUALITY-RESEARCH-PROTOCOL.md` — tool-quality and evidence grading
- `product/TOOL-MARKET-REQUIREMENTS.md` — tool-by-tool market requirements matrix
- `product/UTILITY-HUB-RESEARCH-DECISION.md` — research, audit, and decision package
- `product/CODE-PRD-AUDIT.md` — evidence-based implementation baseline
- `product/PRD_CRITIQUE.md` — independent adversarial critique
- `product/CONTRACT-CRITIQUE.md` — fresh independent reviewer perspective

---

## 1. Product definition

SoapCraft Pro is the comprehensive connected public soapmaking utility system: formulate, size, cost, make, cure, price, purchase, inventory, and plan sales — without repeated recipe entry and without mandatory account creation.

Core tool answers are public and anonymous. Account value is persistence, sync, history, and inventory only.

### Product promise

A soapmaker can move from formulation through sizing, costing, production, cure, pricing, and sales planning in one connected workflow, carrying relevant context forward instead of rebuilding the same data in another calculator or spreadsheet. No login is required to receive any core result.

### Product rule

> Deterministic calculation is authoritative. AI may explain deterministic output later; it must never invent chemical quantities or silently modify a formulation.

### Product model

SoapCraft Pro is **not** a gated SaaS dashboard. It is a comprehensive public utility system with optional connected persistence:

```text
Anonymous Tool Result
  → Recipe / Batch Context (local, versioned)
  → Continue to compatible tool without re-entry
  → Optional account for cloud persistence, sync, history, inventory
  → Optional paid artifact (Seller Pack) after value delivered
```

The **Recipe/Batch Context** is the central shared object. Every tool reads from and writes to this context, carrying forward only the fields the user entered or explicitly accepted. Cure and cost are views of batch context, not orphan calculators.

### Core distinction from traffic-first model

The traffic-first model framed SoapCraft Pro around email capture, CRM drip sequences, subscriptions, and gated content. This contract replaces that framing entirely: the product is a comprehensive public utility system where core calculations are always free and anonymous, account value is persistence only, and monetization follows a contextual-affiliates-first sequence gated by observed demand.

---

## 2. Goal system

### Primary goal metric

**Weekly anonymous utility sessions that produce a correct result, plus the proportion that continue into a connected tool using the same recipe/batch context.**

Initial product target is to establish a measured baseline. Do not invent a target before real traffic exists.

### Activation metric

**First anonymous completion rate:** percentage of new visitors who complete a full calculation and receive a complete result without authentication in their first session.

### Supporting metrics

- `calculation_started` → `calculation_completed` rate
- `calculation_completed` → `connected_tool_opened` rate
- Connected session depth (number of tools used per session)
- `plan_exported` / `share_link_created` rate
- `account_save_requested` rate
- `workspace_interest_submitted` rate
- Returning anonymous visitor rate
- Calculation test suite passes all independently verified vectors

### Guardrail metrics

- Zero unauthorized cross-user data access
- Zero marketing claims for unimplemented behavior
- Zero silent save failures
- Zero chemical quantity generated by AI
- Calculation test suite passes all independently verified vectors
- No historical batch loses its recipe-version snapshot
- No anonymous result requires login, email, cookie consent, or payment

### Monetization guardrails

- Core calculations remain free forever
- First paid test is a one-time Seller Pack, not a subscription
- Paid workspace only after repeat demand observed
- Ads only after traffic evidence exists
- Affiliate links contextual, disclosed, editorially selected

---

## 3. Users and jobs

### Primary: selling-curious / early commercial soapmaker

- Produces approximately 1–20 batches monthly.
- Planning a market stall or first wholesale order.
- Has natural next-step demand for templates, supplies, labels, packaging.
- Job: "When I formulate or resize a recipe, calculate every dependent amount correctly and show me the assumptions. When I plan a batch for sale, help me know what it truly costs, what each saleable bar must earn, how many I need to sell, and when I must make it."

### Secondary: careful beginner / hobbyist

- Needs strong safety boundaries and a clear first workflow.
- May repeat batches occasionally.
- Job: "Help me prepare a valid formulation and keep a complete record without hiding risk."

### Tertiary: experienced soapmaker replacing spreadsheets

- Already has formulations and workflows.
- Needs better tooling than spreadsheets and printed sheets.
- Job: "Help me move from recipe to mold, purchasing, production, cure, pricing, or a sales event without re-entering the same data."

### Explicit user constraints

- Calculations must be immediate and explainable.
- Core results work without login, email, cookie consent, or payment.
- Account must never be required to reveal a core result.
- The interface must not imply a save occurred when data is only local.
- Cure readiness remains a user decision; the product provides elapsed time and observations, not a safety declaration.
- Mobile tool use must work with wet/gloved hands and large controls.

---

## 4. Stable capability IDs

Every in-scope capability has a stable ID that persists across planning, build, and acceptance cycles.

### 4.1 Formulation and chemistry (`CHEM-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| CHEM-001 | NaOH formulation | Calculate lye required for NaOH-only formulations using sourced SAP values |
| CHEM-002 | KOH formulation | Calculate lye required for KOH formulations (bar/milled soap) |
| CHEM-003 | Mixed-alkali formulation | Calculate lye split for NaOH/KOH blends with proper semantics |
| CHEM-004 | Superfat / lye discount | Apply superfat or lye discount with explicit warnings |
| CHEM-005 | Water mode calculation | Support lye concentration, water-to-lye ratio, and percent-of-oils modes |
| CHEM-006 | Oil/fatty-acid profiles | Accept oil blend percentages with sourced SAP values and properties |
| CHEM-007 | Quality indicators | Calculate hardness, condition, iodine, and other quality metrics |
| CHEM-008 | Bounded additives/fragrance | Accept bounded additive and fragrance inputs with safety disclaimers |
| CHEM-009 | Versioned source provenance | Every formula output carries calculator version and dataset revision |
| CHEM-010 | Chemistry verification gate | Deterministic spec, source manifest, independent review, cross-calculator fixtures required before public release |

### 4.2 Sizing and conversion (`SIZE-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| SIZE-001 | Percentage/weight conversion | Convert between percentage and weight inputs |
| SIZE-002 | Unit conversion | Convert g, kg, oz, lb with tested conversion functions |
| SIZE-003 | Recipe scaling | Scale recipes to target batch weights proportionally |
| SIZE-004 | Mold volume/capacity | Calculate mold capacity from volume or dimensions |
| SIZE-005 | Recipe-to-mold sizing | Size a recipe to fit a specific mold |
| SIZE-006 | Target batch weight | Back-calculate ingredient amounts from target weight |
| SIZE-007 | Bar-count / cut planning | Plan bar counts and cuts from batch volume |
| SIZE-008 | Multi-mold allocation | Allocate a batch across multiple molds |
| SIZE-009 | Masterbatch calculations | Approved masterbatch scaling |

### 4.3 Costing and pricing (`COST-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| COST-001 | Ingredient costing | Calculate material cost from ingredient costs and quantities |
| COST-002 | Packaging costing | Calculate packaging cost per saleable unit |
| COST-003 | Labor costing | Calculate labor cost from minutes and rate |
| COST-004 | Overhead costing | Allocate batch overhead |
| COST-005 | Waste and yield adjustment | Account for waste, trim, samples, defects |
| COST-006 | Markup calculation | Calculate markup % from cost and price |
| COST-007 | Gross margin calculation | Calculate gross margin % (separate from markup) |
| COST-008 | Retail/wholesale/channel scenarios | Compare multiple selling scenarios |
| COST-009 | Minimum viable price | Solve algebraic target price before fees |
| COST-010 | Cost per made/saleable unit | Separate cost per made unit and cost per saleable unit |
| COST-011 | Missing-cost warnings | Flag incomplete economics explicitly |

### 4.4 Markets and sales (`MKT-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| MKT-001 | Craft-fair break-even | Calculate break-even units for a craft fair |
| MKT-002 | Product mix planning | Plan multiple products with mix shares and contributions |
| MKT-003 | Stock and revenue planning | Plan stock targets and projected revenue |
| MKT-004 | Sell-through planning | Plan for expected sell-through rates |
| MKT-005 | Target-profit planning | Calculate required units for target profit |
| MKT-006 | Wholesale MOQ planning | Calculate production requirements for wholesale minimums |
| MKT-007 | Quote/price-sheet output | Generate printable quote or price sheet |
| MKT-008 | Event break-even units | Ceiling of fixed event costs ÷ weighted contribution per unit |

### 4.5 Production and cure (`PROD-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| PROD-001 | Pour date calculation | Calculate pour date from ready-by date and cure interval |
| PROD-002 | Unmold/cut date calculation | Calculate unmold and cut dates |
| PROD-003 | Target-ready date | Back-plan from target-ready date |
| PROD-004 | Capacity back-planning | Calculate batches needed per week to meet demand |
| PROD-005 | Batch/lot records | Create and track batch/lot records |
| PROD-006 | Cure tracking | Log cure observations with computed cure day |
| PROD-007 | Printable records | Generate printable batch and cure records |
| PROD-008 | Making session workflow | Step-by-step production with checklist and timer |

### 4.6 Purchasing and inventory (`PURCH-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| PURCH-001 | Ingredient requirements | Calculate ingredient requirements from a formulation |
| PURCH-002 | Packaging requirements | Calculate packaging requirements |
| PURCH-003 | Pack rounding | Round to supplier pack sizes |
| PURCH-004 | Supplier comparison | Compare costs across suppliers |
| PURCH-005 | Requirements minus stock | Show remaining need after accounting for existing stock |
| PURCH-006 | Event counts | Calculate purchase needs for specific event quantities |
| PURCH-007 | Anonymous local planning | Local purchase planning without account |
| PURCH-008 | Optional-account persistence | Account-backed purchase records with sync |
| PURCH-009 | Reusable supplier/item cost records | Save and reuse supplier and cost records |
| PURCH-010 | Inventory depletion tracking | Track inventory depletion across batches |

### 4.7 Utility-support system (`UTIL-*`)

| ID | Capability | Description |
|----|-----------|-------------|
| UTIL-001 | Homepage and tool directory | Complete index of all public utilities |
| UTIL-002 | Methodology pages | Substantive methodology documentation |
| UTIL-003 | Decision guides | Substantive decision guides linked to tools |
| UTIL-004 | Editable examples | Worked examples with editable inputs |
| UTIL-005 | Templates | Downloadable artifacts (costing workbook, planner, etc.) |
| UTIL-006 | Factual comparisons | Verified tool comparisons with provenance |
| UTIL-007 | Canonical SEO architecture | robots.txt, sitemap, metadata, schema, canonical URLs |
| UTIL-008 | Visual explanations | Relevant visual aids for formulas and workflows |

---

## 5. Complete states

### 5.1 Recipe states

```text
draft → validating → ready → versioned → archived
```

- **draft**: Incomplete, not yet validated
- **validating**: Being checked against domain rules
- **ready**: All blocking validations passed; ready to create a version
- **versioned**: An immutable RecipeVersion was created
- **archived**: No longer active; historical references preserved

### 5.2 Batch states

```text
draft → ready_to_make → making → curing → ready → archived
```

Allowed exceptional transitions:

```text
making → abandoned
curing → abandoned
ready → curing (only with reason and audit event)
```

- **draft**: Batch created but not yet started
- **ready_to_make**: All preparations complete; safety checklist pending
- **making**: Production in progress; Making Session active
- **curing**: Batch poured and in cure; observations being logged
- **ready**: Cure complete; yield recorded; cost calculable
- **archived**: Finalized and stored historically
- **abandoned**: Batch discontinued at making or cure stage

### 5.3 Calculation states

```text
input → computing → result → warning → blocking_error
```

- **input**: User has entered some inputs
- **computing**: Deterministic calculation in progress (immediate)
- **result**: Complete calculation with outputs
- **warning**: Result has informational or review-level warnings
- **blocking_error**: Calculation cannot complete; user must fix inputs

### 5.4 Persistence states

```text
unsaved → saving → saved → save_failed
```

- **unsaved**: Local-only, not persisted
- **saving**: Persistence in progress
- **saved**: Confirmed persisted (local or cloud)
- **save_failed**: Persistence failed; user input preserved

### 5.5 Purchase planning states

```text
requirements → pack_rounded → supplier_compared → purchased → depleted
```

- **requirements**: Calculated need from formulation
- **pack_rounded**: Rounded to supplier pack sizes
- **supplier_compared**: Compared across suppliers
- **purchased**: Order placed or cost recorded
- **depleted**: Inventory reduced by batch usage

### 5.6 Monetization states

```text
free_user → seller_pack_requested → seller_pack_delivered → workspace_interest_submitted → workspace_activated
```

- **free_user**: Using core tools anonymously or with account, no payment
- **seller_pack_requested**: Requested one-time Seller Pack artifact
- **seller_pack_delivered**: Artifact delivered with explicit consent
- **workspace_interest_submitted**: Expressed interest in paid workspace after demand observed
- **workspace_activated**: Workspace activated only after repeat demand evidence

### 5.7 Account states (optional)

```text
no_account → account_created → email_verified → persisted → synced
```

- **no_account**: Anonymous usage; all data local
- **account_created**: Account exists; may have no persisted data yet
- **email_verified**: Email confirmed for delivery artifacts
- **persisted**: Data synced to cloud
- **synced**: Multi-device sync active

---

## 6. Non-goals

- **Automatic cure-safety prediction** — cure readiness is the user's decision; the product provides elapsed time and observations only
- **Universal fragrance recommendations** or claims of IFRA compliance certification
- **Regulatory/legal compliance guarantees** — business outputs are planning aids, not advice
- **Bookkeeping, tax filing, e-commerce, or full ERP features**
- **Display-ad integration** as a primary revenue model before traffic evidence
- **Community/forum creation** — ratings, comments, follows, or public profiles
- **Automated publication of content** — every page must pass content acceptance criteria
- **Mandatory account creation** for any core calculation
- **Exit-intent email capture** or fake case studies
- **Gated workspace** as the primary product framing
- **Subscription lifecycle** as core entitlement model
- **AI-generated chemical quantities** — AI may explain deterministic output; it must never invent quantities
- **Priced subscription tiers** before repeat demand is observed
- **Native mobile applications** (responsive web is the target)
- **Multi-language support**
- **Advanced compliance reports**
- **Automated declaration that soap is safe or cured**
- **CRM drip sequences** or generic newsletter gates
- **Email capture as primary conversion path** for core tools

---

## 7. Safety and account boundaries

### 7.1 Anonymous-first safety

- Public tool routes must not require authentication. Every public API route must serve anonymous requests.
- Every private query includes user ownership in the database predicate.
- Child-object access verifies ownership through its parent batch/recipe.
- Client-supplied `userId`, `createdBy`, totals, tier, and price calculations are never trusted.
- Rate-limit mutation paths, including anonymous calculation endpoints.
- Recipe reads never return all users' data.

### 7.2 Account boundaries

- An account must never be required to reveal a core result.
- Account value is limited to: cloud persistence, sync, history, inventory, batch/lot records.
- Account creation is opt-in and never gates a calculation.
- Email is exchanged only for a specific delivered artifact with explicit consent.
- Share state contains no email/personal data. Analytics contain no recipes, notes, or addresses.

### 7.3 Chemistry safety boundary

- No existing SAP, KOH, mold-density, fragrance, or IFRA logic is made public by middleware-only changes.
- Chemistry is in the approved build scope, but it cannot become public until its deterministic specification, source manifest, effective/revision dates, independent review, hand/reference calculations, and cross-calculator fixtures pass.
- The model may research, derive, explain, implement and test chemistry logic, but model output is never the authoritative source of a safety-critical constant or formula.
- Differences between authoritative sources or credible calculators must be explained and resolved; values must not be averaged merely to make tests pass.
- Disclaimers describe scope but never substitute for correct calculations.

### 7.4 Business output boundary

- Business outputs are planning aids, not tax/legal/regulatory advice.
- Cure readiness is always the user's decision; the product provides elapsed time and observations, never a safety declaration.
- Costing outputs with missing inputs are explicitly incomplete and cannot be styled as recommendations.

---

## 8. Central shared Recipe/Batch Context

The **Recipe/Batch Context** is the central shared object that carries forward between tools. It contains only the fields the user entered or explicitly accepted. Every tool reads from and writes to this context.

```ts
type RecipeBatchContext = {
  recipeId?: string;
  recipeVersionId?: string;
  batchId?: string;
  recipeName?: string;
  method?: string;
  targetOilWeight?: number;
  storageUnit?: string;
  oilBlend?: Array<{
    ingredientId: string;
    canonicalName: string;
    percentage: number;
    exactWeight?: number;
  }>;
  superfat?: number;
  lyeType?: "NaOH" | "KOH" | "dual";
  lyeAmount?: number;
  waterAmount?: number;
  waterMode?: "lye_concentration" | "water_to_lye_ratio" | "percent_of_oils";
  fragranceIdentity?: string;
  fragranceLoad?: number;
  additiveInputs?: Array<{ ingredientId: string; amount: number }>;
  moldInputs?: { volume?: number; dimensions?: string };
  calculationOutputs?: {
    oilWeights: Array<{ ingredientId: string; weight: number; unit: string }>;
    alkaliAmount: number;
    waterAmount: number;
    fragranceAmount: number;
    totalBatchMass: number;
    warnings: Array<{ severity: "info" | "review" | "blocking"; message: string }>;
    calculatorVersion: string;
    datasetRevision: string;
  };
  economics?: BatchEconomicsResult;
  sellingScenario?: SellingScenarioResult;
  productionPlan?: ProductionRequirement;
  readyByPlan?: ReadyByPlanResult;
};
```

### Context transfer rules

1. Only fields the user entered or explicitly accepted are carried forward.
2. Calculation outputs are copied as immutable snapshots.
3. Each tool may add to the context but must not overwrite another tool's outputs without explicit user action.
4. Context carries a version chain so provenance is traceable.
5. Local context is browser-scoped; account context is cloud-synced.
6. Context must never contain email, personal data, or analytics identifiers.

---

## 9. Page and content inventory

### 9.1 Public tool pages

```text
/tools                          — Complete tool directory
/tools/formulation/*            — Formulation calculators (NaOH, KOH, mixed)
/tools/sizing/*                 — Sizing and conversion tools
/tools/batch-economics          — Cost and pricing calculator
/tools/pricing/*                — Pricing scenario tools
/tools/markets/craft-fair-break-even — Craft fair break-even calculator
/tools/production/ready-by-planner — Production back-planning tool
/tools/purchasing/*             — Purchase planning tools
```

### 9.2 Content pages

```text
/                              — Homepage (proof-led utility overview)
/blog                          — Blog index
/blog/[slug]                   — Individual articles
/guides/[slug]                 — Substantive decision guides
/examples/*                    — Editable worked examples
/templates/*                   — Downloadable artifacts
/compare/*                     — Factual comparisons
```

### 9.3 Account pages (optional)

```text
/dashboard                     — Production overview
/recipes                       — Recipe portfolio
/recipes/[recipeId]            — Recipe detail
/recipes/[recipeId]/versions/[versionId] — Version history
/batches                       — Batch portfolio
/batches/[batchId]             — Batch detail
/batches/[batchId]/making      — Making Session
/cure                          — Cure portfolio
/costing                       — Cost portfolio
/ingredients                   — Ingredient inventory
/settings/*                    — Profile, preferences, billing, data
```

### 9.4 Legal and safety pages

```text
/legal/privacy                 — Privacy policy
/legal/terms                   — Terms of service
/legal/safety                  — Safety disclaimer
```

### 9.5 Content quality rules

Every published page must supply at least one of:
- A verified working tool
- An editable worked calculation
- A useful downloadable artifact
- Verified reference data with provenance
- Substantive synthesis of real workflow evidence

No page ships solely to meet a word/page quota. Guide pages should generally provide approximately 1,500+ rendered words where the subject warrants depth, plus useful visuals and direct tool connections. Safety, legal, tax, IFRA, and formulation content needs named sources and reviewer approval.

---

## 10. Success metrics and release standard

### 10.1 Technical release standard

All of the following must pass:

1. Anonymous user completes the full flow in a fresh browser with no login, email, cookie consent dependency, or payment.
2. Inputs transfer between all tool stages without re-entry.
3. Results show formulas, definitions, assumptions, rounding policy, and missing-cost warnings.
4. Markup and gross margin are separately labeled and verified against reference cases.
5. Saleable yield changes cost-per-bar and all downstream outputs consistently.
6. Event fees, percentage fees, fixed transaction fees, labor, and target profit affect results correctly.
7. Date planning uses an explicit user-selected interval and never claims to determine product safety/readiness.
8. Share state contains no email/personal data; analytics contain no recipes, notes, or addresses.
9. Export contains the same values/formula revision as the screen.
10. Error states are accessible and preserve valid inputs.
11. Typecheck, lint, unit tests, production build, and anonymous mobile/desktop E2E all pass.
12. Public page/API responses are 200; sitemap and robots are 200 and correct.
13. Canonical URLs contain no duplicate `/marketing` tree.
14. PostHog events follow the approved event contract and omit sensitive values.
15. No endpoint reports email delivery, save, export, or payment success unless the side effect is verified.
16. Formula/data revisions are explicit and included in exports.
17. Error logging does not expose user-entered recipe or contact data.
18. Pure calculation modules have unit, boundary, property, and unit-conversion round-trip tests.
19. Independent spreadsheet/reference cases are reviewed before release.

### 10.2 Safety release standard

All of the following must be true before any chemistry feature becomes public:

1. Deterministic specification documented and version-controlled.
2. Source manifest with effective/revision dates.
3. Independent review by a named domain owner.
4. Hand/reference calculations verified.
5. Cross-calculator fixtures passing independently.
6. No averaged values to make tests pass.
7. Differences between authoritative sources explained and resolved.

### 10.3 Content release standard

All of the following must be true before content goes live:

1. Every page supplies at least one of: verified working tool, editable worked calculation, useful downloadable artifact, verified reference data with provenance, or substantive synthesis of real workflow evidence.
2. No page ships solely to meet a word/page quota.
3. SEO infrastructure (robots.txt, sitemap, metadata, schema) exists before any content publishes.
4. Canonical URLs are correct and consistent.

### 10.4 Utility signal milestones

1. **Technical release gate:** 100% of selected public pages return 200 anonymously; zero high-severity formula failures; sitemap/robots public; lint/typecheck/tests/build/E2E pass.
2. **Utility signal:** collect at least 100 genuine completed utility sessions before judging downstream behavior.
3. **Workflow signal:** at least 15% of completed sessions continue to a connected result. If lower, revise the seam and relevant tool handoff.
4. **Repeat signal:** observe meaningful returning-tool usage over four weeks; segment by use case rather than using a vanity visitor count.
5. **Offer signal:** measure worksheet delivery and paid-resource interest; build a workspace only if save/multi-batch/inventory requests recur.
6. **SEO signal:** review index coverage, query-page fit, impressions, clicks, and pages with zero impressions after sufficient crawl time; consolidate rather than endlessly publish.

These thresholds are internal falsification criteria. They are not revenue forecasts.

### 10.5 Definition of done

The comprehensive utility hub is done only when a clean test user can:

1. Visit the homepage and see the connected workflow without authentication.
2. Use any public tool and receive a complete result without login, email, cookie consent, or payment.
3. View formulas, assumptions, warnings, and methodology.
4. Continue between connected tools without re-entry.
5. Create a local, versioned Recipe/Batch Context containing only entered/accepted fields.
6. Print/export/share the current plan locally.
7. Optionally create an account for cloud persistence, sync, history, or inventory.
8. Optionally request a Seller Pack after receiving the useful result.
9. See all calculations verified against independently reviewed reference cases.
10. Confirm that no anonymous flow requires authentication to reveal a core result.
11. Log out and confirm no cross-user data access.
12. Visit public pages and confirm they return 200, are indexable, and have correct sitemap/robots.

A route, component, database table, static card, alert, console log, or demo record does not satisfy these acceptance criteria.

---

## 11. Monetization contract

### Revenue sequence

1. **Contextual affiliate links** — after a result, only where the product/use case is genuinely relevant; disclosed and editorially selected.
2. **One-time Seller Pack** — editable costing workbook, market planner, batch/cure sheet, wholesale quote sheet, and inventory count sheet; first paid test, not a subscription.
3. **Optional email sequence** — tied to a specific delivered artifact with explicit consent; never a generic newsletter gate.
4. **Display ads** — only after enough traffic exists to assess user impact and network eligibility; no revenue claim is made now.
5. **Paid workspace** — only after users demonstrate recurring save, multi-batch, inventory, or lot-tracking behaviour.

### Core rules

- Core calculations remain free forever.
- An account must never be required to reveal a core result.
- No subscription prompt until repeat-use evidence exists.
- Paid workspace only after repeat saving/multi-batch/inventory demand is observed.
- Ads require a separate UX/performance decision after traffic evidence.
- Email is exchanged only for a specific delivered artifact with explicit consent.
- Affiliate links are contextual, disclosed, and editorially selected.
- No fake case studies, fabricated testimonials, or invented earnings claims.

### Superseded billing artifacts

The following traffic-first billing artifacts are superseded and must not be implemented as product authority:

- Dodo subscription lifecycle as core entitlement model
- Free tier: Calculator + 3 recipes + 1 active batch
- Pro tier: $12/month or $99/year
- Trial: "Not available in v1" (replaced: no trial gate for core tools)
- Subscription billing (DEFERRED): Only after observed demand for workspace features
- Subscription state machine as primary entitlement

These artifacts are retained as historical audit evidence only. They are not the approved product direction.

---

## 12. Measurement contract

### Required events

- `tool_viewed`
- `calculation_started`
- `calculation_completed`
- `connected_tool_opened`
- `plan_exported`
- `share_link_created`
- `email_delivery_confirmed`
- `affiliate_link_clicked`
- `account_save_requested`
- `workspace_interest_submitted`

### Event properties

Properties: tool, source page, device class, new/returning, anonymous flow ID, and validation/error category. Do not send ingredient notes, email addresses, or full recipes to analytics. Analytics contain no recipes, notes, or addresses.

### Measurement validation

Initial validation needs at least 100 genuine completed utility sessions. A working hypothesis is that 15% or more continue to a connected output; below that, revise the seam and relevant tool handoff. This measurement improves the comprehensive hub after release; it is not a gate that postpones the approved initial tool/content architecture.

---

## 13. Tool-quality and market-research contract

Before a tool implementation is accepted, its specification must be grounded in direct inspection of the strongest current alternatives for that exact job. The audit must record:

- Supported inputs, modes, settings, and units
- Formulas, terminology, rounding, and visible assumptions
- Source datasets and provenance where discoverable
- Result depth, warnings, error handling, and mobile behavior
- Local/cloud saving, export, sharing, and cross-tool handoffs
- User complaints, spreadsheet/manual workarounds, and switching costs
- What SoapCraft Pro must match, must improve, uniquely connects, and must avoid
- Unresolved safety, licensing, source, or domain-review gates

The result is a tool-by-tool market requirements matrix with dated URLs and evidence strength. Generic competitor summaries do not satisfy this requirement. A route or calculator name cannot enter the final acceptance ledger until its matrix row and deterministic behavior contract exist.

Research and evidence grading are governed by `product/TOOL-QUALITY-RESEARCH-PROTOCOL.md`; no delegated or competitor assertion may bypass that protocol.

---

## 14. Technical requirements

### 14.1 Calculation modules

- Pure calculation modules have unit, boundary, property, and unit-conversion round-trip tests.
- Independent spreadsheet/reference cases are reviewed before release.
- No AI or network call may sit in the quantity-calculation path.
- Formula/data revisions are explicit and included in exports.
- Money must never be summed across currencies.
- Quantities must be normalized by tested conversion functions.
- Rounding is display-only until the final monetary output.
- Error logging does not expose user-entered recipe or contact data.

### 14.2 Application quality

- Typecheck, lint, unit tests, production build, and anonymous mobile/desktop E2E all pass.
- Public page/API responses are 200; sitemap and robots are 200 and correct.
- Canonical URLs contain no duplicate `/marketing` tree.
- PostHog events follow the approved event contract and omit sensitive values.
- No endpoint reports email delivery, save, export, or payment success unless the side effect is verified.
- Formula/data revisions are explicit and included in exports.
- Error logging does not expose user-entered recipe or contact data.

### 14.3 Performance and reliability

- Deterministic calculation response: under 100ms on supported client hardware.
- No network dependency for quantity calculation.
- Dashboard useful-content server response target: under 1 second at p75 excluding cold start.
- Core Web Vitals target: green at p75.
- Timer resumes from server timestamps after reload.
- Mutations are idempotent where retries are likely: client supplies a mutation UUID unique within user + operation; the database enforces uniqueness; a payload-hash mismatch on key reuse returns conflict; an exact replay returns the original outcome.
- No zero-value fallback that appears to be real cost/data.
- Production errors use observability without exposing secrets or user notes.

### 14.4 Accessibility and responsive

- WCAG 2.2 AA target.
- Keyboard operation for all controls.
- Visible focus states.
- Semantic tables with row headers and mobile list alternative.
- Statuses conveyed by icon/text, not color alone.
- 44×44px targets in Making Mode and mobile primary actions.
- `aria-live` for calculation and save results.
- Reduced-motion support.
- 200% zoom without content loss.
- Numeric inputs use appropriate input mode and explicit units.
- Safety information remains reachable and does not obscure content.

### 14.5 Local/share URL/cloud persistence

- Local state is browser-scoped and clearly labeled as local-only.
- Share URLs encode the full context as a URL-safe snapshot; contain no email or personal data.
- Cloud persistence requires account creation; syncs across devices.
- Share URLs and local state must be distinguishable from account-backed data.
- Local state survives page reload within the browser session; explicit export preserves data beyond the session.

---

## 15. Approval gates

1. **Product direction:** approved by Isaac on 2026-09-09, including comprehensive scope, current expansion, and chemistry subject to verification.
2. **Baseline recovery:** credential rotated, branch/worktree/stash backed up, deployed commit identified.
3. **Market/tool specification:** detailed direct-source benchmark and tool-quality matrix completed.
4. **Formula specification:** chemistry, sizing, and economic formulas plus reference fixtures reviewed.
5. **Chemistry verification gate:** deterministic specification, source manifest, effective/revision dates, independent review, hand/reference calculations, and cross-calculator fixtures all pass before any chemistry feature becomes public.
6. **Comprehensive release:** all approved functional, technical, safety, content, and SEO acceptance criteria pass through independent acceptance gate.
7. **Post-release improvement:** individual tools are iterated from observed use, search, support, and competitive evidence.
8. **Spending/publishing:** explicit approval for ads, paid traffic, partnerships, chemistry features, and bulk publication.

---

## 16. Superseded artifacts register

The following items from traffic-first planning are superseded evidence, not authority:

| Traffic-first artifact | Status | Superseded by |
|----------------------|--------|---------------|
| Email capture with false "Welcome email sent" | Superseded | Email only for specific delivered artifact with consent |
| Exit-intent email capture | Superseded | No exit-intent capture |
| CRM drip sequence | Superseded | Optional email tied to specific delivered artifact |
| Four-tool MVP scope | Superseded | Comprehensive seven-category scope |
| Gated workspace as primary framing | Superseded | Anonymous utility hub with optional persistence |
| Free tier / Pro tier pricing ($12/mo, $99/yr) | Superseded | Core calculations free; paid after demand observed |
| Subscription state machine as entitlement | Superseded | Utility-first; account for persistence only |
| `/marketing` route tree | Superseded | Canonical `/blog`, `/guides`, `/tools` tree |
| Pricing page as public priority | Superseded | Tool directory as public priority |
| SaaS-first homepage framing | Superseded | Proof-led utility homepage |
| Pinterest/TikTok as primary distribution | Superseded | SEO-first discoverability; social as supplementary |

These artifacts are retained for historical audit only. They must not be used as authority for any product decision going forward.

---

*This document replaces `product/PRD.md` v3.0 and v4.0 traffic-first artifacts. The approved direction from `product/PRODUCT-CONTRACT-UTILITY-HUB.md` governs all product decisions. The chemistry engine remains subject to the verification gate in §7.3 before any public release.*
