import Link from "next/link";
import { ArrowUpRight, Beaker, Check, LockKeyhole } from "lucide-react";
import { canonicalRoutes } from "@/lib/routing/canonical-routes";

const descriptions: Record<string, string> = { formulation: "Enter an oil blend and process configuration. Public chemistry quantities stay gated until the evidence boundary is approved.", "mold-volume": "Calculate capacity from rectangular, cylindrical, or measured fill inputs.", "recipe-scaling": "Scale ingredient quantities on an explicit basis without relabelling copy mode as chemistry verification.", "batch-cost": "Separate materials, packaging, labor, overhead, yield, and cost per saleable unit.", "wholesale-pricing": "Solve a wholesale and retail scenario from a real unit cost.", "craft-fair-break-even": "Model event costs, product mix, contribution, sell-through, and stock needs.", "ready-by-planner": "Work backward from a date-only ready-by target and cure interval.", "ingredient-purchase-planner": "Subtract usable stock and calculate the packs needed for a planned requirement." };

export default function ToolsPage() {
  return <main className="min-h-screen overflow-x-hidden"><section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 md:py-20"><div className="max-w-3xl"><p className="eyebrow">The toolbox</p><h1 className="mt-4 text-5xl leading-tight sm:text-6xl">Eight decisions around one batch.</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Each tool works without an account. Use one now, or keep moving through the chain while the context is still fresh.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{canonicalRoutes.map((tool, index) => { const gated = tool.isGated; return <article key={tool.slug} className={`group flex min-h-[290px] flex-col rounded-3xl border p-6 transition ${gated ? "border-accent/50 bg-accent/10" : "border-border bg-card hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl hover:shadow-primary/10"}`}><div className="flex items-center justify-between"><span className="font-mono text-sm text-muted-foreground">0{index + 1}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${gated ? "bg-accent text-accent-foreground" : "bg-primary/10 text-primary"}`}>{gated ? "Safety boundary" : "Ready to use"}</span></div><h2 className="mt-9 text-2xl">{tool.title}</h2><p className="mt-3 flex-1 leading-7 text-muted-foreground">{descriptions[tool.slug]}</p>{gated ? <div className="mt-5 flex items-center gap-2 text-sm font-semibold text-muted-foreground"><LockKeyhole className="h-4 w-4" />Methodology available; quantities gated</div> : <Link href={tool.path} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Open tool <ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></Link>}</article>; })}</div><div className="mt-12 grid gap-4 rounded-3xl bg-foreground p-6 text-background sm:grid-cols-3 sm:p-8"><div className="flex gap-3"><Check className="mt-1 h-5 w-5 shrink-0 text-accent" /><p className="text-sm leading-6 text-background/75">Anonymous-first: calculate, save locally, print, export, and share.</p></div><div className="flex gap-3"><Check className="mt-1 h-5 w-5 shrink-0 text-accent" /><p className="text-sm leading-6 text-background/75">Inputs and assumptions remain visible at the result boundary.</p></div><div className="flex gap-3"><Beaker className="mt-1 h-5 w-5 shrink-0 text-accent" /><p className="text-sm leading-6 text-background/75">Safety-sensitive chemistry fails closed until evidence is ready.</p></div></div></section></main>;
}
