// ── SLICE-002: Schema Index ──
export {
  CONTEXT_SCHEMA_VERSION,
  CONTEXT_NAMESPACE_PREFIX,
  MAX_SHARE_URL_LENGTH,
  type ToolId,
  type SourceTool,
  type FieldOrigin,
  type FormulationContext,
  type MoldContext,
  type ScalingContext,
  type YieldContext,
  type CostingContext,
  type PricingContext,
  type EventContext,
  type ProductionContext,
  type PurchasingContext,
  type RecipeBatchContextV1,
  isValidContextVersion,
  isValidToolId,
  isValidFieldOrigin,
  isValidContextId,
  validateContextShape,
  createContextId,
  nowISO,
  getContextStorageKey,
} from "./context-schema";
